"""MeetingMind AI — Demo Mode seeding (REAL media through the REAL pipeline).

Builds a complete demo workspace for a single demo account so a recruiter or
evaluator can experience the whole product. Unlike a fixture dump, **nothing here
is fabricated**: for every scripted meeting we take the real audio/video file
generated by :mod:`apps.common.demo_media` and push it through the exact same
pipeline a user's upload goes through —

    create_upload()  →  Faster-Whisper transcription  →  Ollama AI analysis
      →  AISuggestions (auto-approved into Tasks/Decisions/Risks per mode)
      →  knowledge indexing  →  executive materialization

so the transcripts, summaries, action items and dashboards are genuinely
computed by the product. On top of that we run a few real grounded chat Q&As and
a few real agent runs so those surfaces have authentic history.

The one deviation from a live upload: we suppress the pipeline's auto-dispatch
just long enough to attach the meeting to its demo Project *before* processing
runs, so every derived record (suggestions, knowledge items, executive rollups)
is correctly project-scoped. We then run the pipeline synchronously ourselves.

This is the single source of truth used by the ``create_demo`` management
command, ``scripts/create_demo.py`` and the ``POST /api/demo/reset/`` endpoint.

Entry point: ``seed_demo(reset=True)``.
"""
from __future__ import annotations

import logging
import random
from datetime import timedelta

from django.conf import settings
from django.core.files.uploadedfile import SimpleUploadedFile
from django.utils import timezone

import apps.jobs.manager as jobs_manager
from apps.accounts.models import User
from apps.common import demo_media
from apps.common.demo_data import (  # noqa: F401 — DEMO_* re-exported for importers
    DEMO_EMAIL,
    DEMO_FIRST,
    DEMO_LAST,
    DEMO_PASSWORD,
    MEETINGS,
    PROJECTS,
    WORKSPACE_NAME,
    MeetingSpec,
)
from apps.jobs.services import execute_job
from apps.meetings.enums import MeetingSource, ProcessingStatus
from apps.meetings.models import Meeting, MeetingJob, Transcript
from apps.meetings.services.uploads import create_upload

logger = logging.getLogger("meetingmind")

# During seeding we auto-approve reasonably-confident AI suggestions so the
# Kanban/decisions/risks boards are populated, while lower-confidence ones stay
# in the "AI Approvals" queue (so that surface is populated too).
_SEED_SUGGESTION_MODE = "auto_high"
_SEED_APPROVE_THRESHOLD = 68
# The last N meetings are processed in "suggestions_only" mode so the AI
# Approvals queue (human-in-the-loop) is genuinely populated with pending items.
_PENDING_QUEUE_MEETINGS = 4

# A handful of meetings get real, grounded chat Q&A pre-run (Ollama) so the chat
# panel isn't empty — kept small to keep the seed run practical.
_CHAT_MEETINGS = 5
# Real agent runs to populate the Agent Center history/reputation.
_AGENT_RUNS = [
    ("executive_agent", "Summarise the biggest risks across all projects this quarter."),
    ("risk_analyst_agent", "Which risks are still open and unmitigated?"),
    ("project_manager_agent", "What should we prioritise next sprint for Apollo?"),
    ("knowledge_agent", "What did we decide about authentication?"),
    ("customer_success_agent", "Which customers are at risk of churning?"),
]


class DemoSeeder:
    def __init__(self, log=print, *, force_media: bool = False):
        self.log = log
        self.force_media = force_media
        self.counts = {
            "projects": 0, "meetings": 0, "processed": 0, "transcribed": 0,
            "analyses": 0, "suggestions": 0, "tasks": 0, "decisions": 0, "risks": 0,
            "indexed": 0, "chats": 0, "agent_runs": 0,
            "consensus": False, "executive": False,
        }

    # -- lifecycle ------------------------------------------------------
    def wipe(self):
        existing = User.objects.filter(email=DEMO_EMAIL).first()
        if existing:
            existing.delete()  # hard cascade removes all owner-scoped data
            self.log("  wiped previous demo data")

    def user(self) -> User:
        u = User(email=DEMO_EMAIL, first_name=DEMO_FIRST, last_name=DEMO_LAST, is_active=True)
        u.set_password(DEMO_PASSWORD)
        u.save()
        return u

    # -- per-meeting ----------------------------------------------------
    def _upload_and_process(self, user, spec: MeetingSpec, media_row: dict, project, when):
        """Upload one real file and run the full pipeline synchronously.

        Auto-dispatch is suppressed by the caller so the meeting can be attached
        to its Project before we run the pipeline (so derived records are
        project-scoped). Returns the processed Meeting.
        """
        path = demo_media.media_path(media_row["filename"])
        if path is None:
            raise RuntimeError(f"demo media missing: {media_row['filename']}")
        data = path.read_bytes()
        uploaded = SimpleUploadedFile(
            media_row["filename"], data, content_type=media_row["content_type"]
        )
        outcome = create_upload(
            owner=user,
            uploaded_file=uploaded,
            title=spec.title,
            description=f"{spec.mtype.replace('_', ' ').title()} · {spec.project}",
            language="en",
            source=MeetingSource.MANUAL_UPLOAD,
            tags=[spec.mtype, spec.project],
        )
        meeting = outcome.meeting
        # Attach project + backdate BEFORE running the pipeline so every derived
        # record (suggestions, knowledge items, executive rollups) is scoped right.
        Meeting.objects.filter(pk=meeting.pk).update(
            project=project, created_at=when, updated_at=when
        )

        job = (
            MeetingJob.objects.filter(meeting=meeting)
            .select_related("background_job")
            .order_by("-created_at")
            .first()
        )
        if job is not None:
            execute_job(str(job.background_job_id), worker="demo_seeder")
        meeting.refresh_from_db()
        self._backfill_project(meeting, project)
        return meeting

    @staticmethod
    def _backfill_project(meeting, project):
        """Attach the meeting's project to entities the pipeline materialised.

        ``materialize`` grounds new Tasks/Decisions/Risks to the meeting but not
        to its project (that's a user step in normal use), so we propagate it
        here to keep the demo's per-project boards populated.
        """
        from apps.workspace.models import Decision, FollowUp, Issue, Risk, Task

        for model in (Task, Decision, Risk, Issue, FollowUp):
            model.objects.filter(meeting=meeting, project__isnull=True).update(project=project)

    @staticmethod
    def _is_indexed(meeting) -> bool:
        from apps.knowledge.models import KnowledgeItem

        return KnowledgeItem.objects.filter(meeting=meeting, is_current=True).exists()

    def _record_counts(self, meeting):
        from apps.meetings.models import AIAnalysis
        from apps.workspace.models import AISuggestion, Decision, Risk, Task

        self.counts["processed"] += 1
        if Transcript.objects.filter(meeting=meeting).exists():
            self.counts["transcribed"] += 1
        if AIAnalysis.objects.filter(meeting=meeting).exists():
            self.counts["analyses"] += 1
        self.counts["suggestions"] += AISuggestion.objects.filter(meeting=meeting).count()
        self.counts["tasks"] += Task.objects.filter(meeting=meeting).count()
        self.counts["decisions"] += Decision.objects.filter(meeting=meeting).count()
        self.counts["risks"] += Risk.objects.filter(meeting=meeting).count()

    # -- cross-meeting real AI ------------------------------------------
    def _seed_chats(self, user):
        """Run real, grounded chat Q&A on a few meetings (best-effort)."""
        from apps.meetings.services.chat import ChatService, start_conversation

        service = ChatService()
        meetings = list(
            Meeting.objects.filter(owner=user, processing_status=ProcessingStatus.COMPLETED)
            .order_by("created_at")
        )
        # Prefer meetings that carry scripted questions, spread across projects.
        picks, seen_projects = [], set()
        specs_by_title = {s.title: s for s in MEETINGS}
        for m in meetings:
            spec = specs_by_title.get(m.title)
            if spec and spec.chat and m.project_id not in seen_projects:
                picks.append((m, spec))
                seen_projects.add(m.project_id)
            if len(picks) >= _CHAT_MEETINGS:
                break
        for meeting, spec in picks:
            try:
                conv = start_conversation(meeting, title=spec.chat[0][0][:80], actor=user)
                for question, _ans, _found in spec.chat[:2]:
                    service.ask(conv, question, actor=user)
                self.counts["chats"] += 1
                self.log(f"  chat: {meeting.title}")
            except Exception as exc:  # noqa: BLE001 — needs Ollama; degrade gracefully
                self.log(f"  ! chat skipped for '{meeting.title}' ({type(exc).__name__})")

    def _seed_agent_runs(self, user):
        """Run a few real agents so the Agent Center has authentic history."""
        from apps.agents.framework.executor import AgentExecutor

        executor = AgentExecutor()
        for agent_name, request in _AGENT_RUNS:
            try:
                executor.run(user, agent_name, request)
                self.counts["agent_runs"] += 1
                self.log(f"  agent: {agent_name}")
            except Exception as exc:  # noqa: BLE001 — needs Ollama; degrade gracefully
                self.log(f"  ! agent '{agent_name}' skipped ({type(exc).__name__})")

    # -- orchestration --------------------------------------------------
    def run(self):
        from apps.knowledge.services.consensus import ConsensusService
        from apps.knowledge.services.executive import materialize as exe_materialize
        from apps.workspace.models import Workspace

        # Ensure the real media exists (generate on first run).
        manifest = demo_media.load_manifest()
        if not manifest or self.force_media:
            self.log("  generating demo media (local TTS + ffmpeg)…")
            manifest = demo_media.generate_all(force=self.force_media, log=self.log)
        media_by_index = {r["index"]: r for r in manifest}

        # Seed-time AI settings: auto-approve confident suggestions.
        prev_mode = getattr(settings, "AI_SUGGESTION_MODE", "suggestions_only")
        prev_thresh = getattr(settings, "AI_AUTO_APPROVE_THRESHOLD", 95)
        settings.AI_SUGGESTION_MODE = _SEED_SUGGESTION_MODE
        settings.AI_AUTO_APPROVE_THRESHOLD = _SEED_APPROVE_THRESHOLD

        # Suppress Celery auto-dispatch so we can attach the project before the
        # pipeline runs, then execute each job synchronously ourselves.
        original_dispatch = jobs_manager.JobManager.dispatch
        jobs_manager.JobManager.dispatch = lambda self, job: None

        try:
            self.wipe()
            user = self.user()
            self.log(f"  demo user: {DEMO_EMAIL}")

            ws = Workspace.objects.create(
                owner=user, name=WORKSPACE_NAME,
                description="Explore MeetingMind AI with a workspace built from real recordings.",
            )
            from apps.workspace.enums import ProjectStatus
            from apps.workspace.models import Project

            projects = {}
            for name, desc in PROJECTS:
                projects[name] = Project.objects.create(
                    owner=user, workspace=ws, name=name, description=desc,
                    status=ProjectStatus.ACTIVE,
                )
                self.counts["projects"] += 1

            from apps.knowledge.services.index import KnowledgeIndexService
            idx = KnowledgeIndexService()

            for i, spec in enumerate(MEETINGS):
                row = media_by_index.get(i)
                if row is None:
                    row = demo_media.generate_one(i, spec, log=self.log)
                rng = random.Random(1000 + i)
                when = timezone.now() - timedelta(days=spec.days_ago, hours=rng.randint(0, 6))
                project = projects[spec.project]

                # Keep the last few meetings' suggestions pending so the AI
                # Approvals queue is populated; auto-approve the rest.
                settings.AI_SUGGESTION_MODE = (
                    "suggestions_only"
                    if i >= len(MEETINGS) - _PENDING_QUEUE_MEETINGS
                    else _SEED_SUGGESTION_MODE
                )

                meeting = self._upload_and_process(user, spec, row, project, when)
                self.counts["meetings"] += 1
                self._record_counts(meeting)

                has_tx = Transcript.objects.filter(meeting=meeting).exists()
                # The JOB_COMPLETED subscriber already indexed the meeting (with the
                # project set). Only index explicitly if that somehow didn't happen.
                if not self._is_indexed(meeting):
                    try:
                        idx.index_meeting(meeting)
                    except Exception as exc:  # noqa: BLE001 — embeddings need Ollama
                        self.log(f"    ! indexing skipped for '{spec.title}' ({type(exc).__name__})")
                if self._is_indexed(meeting):
                    self.counts["indexed"] += 1

                tx = "transcript ok" if has_tx else "NO TRANSCRIPT"
                self.log(f"  + {spec.title}  [{row['media']}, {row['duration_seconds']}s, {tx}]")

            # Cross-meeting reasoning + executive materialization (real).
            try:
                ConsensusService().compute(user, persist=True)
                self.counts["consensus"] = True
                self.log("  consensus computed")
            except Exception as exc:  # noqa: BLE001
                self.log(f"  ! consensus skipped ({type(exc).__name__})")
            try:
                exe_materialize(user, actor=user)
                self.counts["executive"] = True
                self.log("  executive dashboards materialized")
            except Exception as exc:  # noqa: BLE001
                self.log(f"  ! executive materialization failed ({type(exc).__name__})")

            self._seed_chats(user)
            self._seed_agent_runs(user)
            return self.counts
        finally:
            jobs_manager.JobManager.dispatch = original_dispatch
            settings.AI_SUGGESTION_MODE = prev_mode
            settings.AI_AUTO_APPROVE_THRESHOLD = prev_thresh


def seed_demo(reset: bool = True, log=print, *, force_media: bool = False) -> dict:
    """Seed (or reset) the demo workspace from real media. Returns a counts summary.

    NOT wrapped in a single transaction: each meeting is uploaded and processed
    through the real pipeline (which commits so on-completion subscribers see the
    data), so partial progress is visible per meeting.
    """
    seeder = DemoSeeder(log=log, force_media=force_media)
    return seeder.run()
