# Generated by Django 5.1.15 on 2026-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="evidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="fallback_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="grounding_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="quality_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="token_usage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="tool_latency_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="validation_issues",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="validation_latency_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="validation_ok",
            field=models.BooleanField(default=True),
        ),
    ]
