# Generated by Django 5.1.15 on 2026-07-09 10:02

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agentrun_completeness_score_agentrun_evidence_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("request", models.TextField(blank=True)),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("fast", "Fast"),
                            ("balanced", "Balanced"),
                            ("highest_quality", "Highest quality"),
                            ("lowest_latency", "Lowest latency"),
                            ("research", "Research"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("single", "Single agent"),
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                            ("conditional", "Conditional"),
                        ],
                        default="parallel",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("pending_approval", "Pending approval"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=18,
                    ),
                ),
                ("intent", models.TextField(blank=True)),
                (
                    "selected_agents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("reasoning", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("found", models.BooleanField(default=True)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("planner_quality", models.FloatField(db_index=True, default=0.0)),
                ("selection_score", models.FloatField(default=0.0)),
                ("merge_quality", models.FloatField(default=0.0)),
                ("grounding_score", models.FloatField(default=0.0)),
                ("evidence_coverage", models.FloatField(default=0.0)),
                ("conflict_resolution_score", models.FloatField(default=100.0)),
                ("planning_ms", models.PositiveIntegerField(default=0)),
                ("execution_ms", models.PositiveIntegerField(default=0)),
                ("merge_ms", models.PositiveIntegerField(default=0)),
                ("validation_ms", models.PositiveIntegerField(default=0)),
                ("total_ms", models.PositiveIntegerField(default=0)),
                ("parallel_efficiency", models.FloatField(default=0.0)),
                ("agent_count", models.PositiveIntegerField(default=0)),
                ("tool_calls", models.PositiveIntegerField(default=0)),
                ("llm_calls", models.PositiveIntegerField(default=0)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planner_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="planner_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_runs",
                to="agents.plannerrun",
            ),
        ),
        migrations.CreateModel(
            name="PlannerStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("analyze", "Analyze intent"),
                            ("decompose", "Decompose"),
                            ("select", "Select agents"),
                            ("execute", "Execute"),
                            ("merge", "Merge"),
                            ("resolve", "Resolve conflicts"),
                            ("validate", "Validate"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("ok", models.BooleanField(default=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.plannerrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="plannerrun",
            index=models.Index(
                fields=["owner", "-created_at"], name="agents_plan_owner_i_b25cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannerrun",
            index=models.Index(fields=["owner", "status"], name="agents_plan_owner_i_e50bd6_idx"),
        ),
        migrations.AddIndex(
            model_name="plannerstep",
            index=models.Index(fields=["run", "order"], name="agents_plan_run_id_0c7990_idx"),
        ),
    ]
