# Generated by Django 5.1.15 on 2026-07-09 10:23

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_plannerrun_agentrun_planner_run_plannerstep_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("workflow", models.CharField(db_index=True, default="custom", max_length=48)),
                ("request", models.TextField(blank=True)),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                            ("review_required", "Review required"),
                            ("debate_required", "Debate required"),
                            ("consensus_required", "Consensus required"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("pending_approval", "Pending human approval"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=18,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("reasoning", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("found", models.BooleanField(default=True)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("collaboration_quality", models.FloatField(db_index=True, default=0.0)),
                ("agreement_rate", models.FloatField(blank=True, null=True)),
                ("review_success_rate", models.FloatField(blank=True, null=True)),
                ("debate_count", models.PositiveIntegerField(default=0)),
                ("tool_reuse_pct", models.FloatField(default=0.0)),
                ("stages_count", models.PositiveIntegerField(default=0)),
                ("agent_count", models.PositiveIntegerField(default=0)),
                ("total_ms", models.PositiveIntegerField(default=0)),
                ("human_required", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planner_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaborations",
                        to="agents.plannerrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollaborationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("produce", "Produce"),
                            ("handoff", "Handoff"),
                            ("review", "Review"),
                            ("vote", "Vote"),
                            ("debate", "Debate"),
                            ("consensus", "Consensus"),
                            ("human_gate", "Human gate"),
                            ("merge", "Merge"),
                        ],
                        max_length=12,
                    ),
                ),
                ("agent", models.CharField(blank=True, max_length=64)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("input", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                (
                    "review",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("approved", models.BooleanField(blank=True, null=True)),
                ("vote", models.CharField(blank=True, max_length=4)),
                ("confidence", models.FloatField(default=0.0)),
                ("quality", models.FloatField(default=0.0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.collaborationrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="collaborationrun",
            index=models.Index(
                fields=["owner", "-created_at"], name="agents_coll_owner_i_b4e941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationrun",
            index=models.Index(fields=["owner", "status"], name="agents_coll_owner_i_d2502e_idx"),
        ),
        migrations.AddIndex(
            model_name="collaborationstep",
            index=models.Index(fields=["run", "order"], name="agents_coll_run_id_7b0788_idx"),
        ),
    ]
