# Generated by Django 5.1.15 on 2026-07-08 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_meeting_project"),
        ("workspace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="source_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="source_segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="source_speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="decision",
            name="source_start_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_analysis_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="followup",
            name="source_start_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="issue",
            name="source_start_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="source_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="source_segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="risk",
            name="source_speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="risk",
            name="source_start_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_segment_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="source_start_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="meetings.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="meetings.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="meetings.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="meetings.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="meetings.meeting",
            ),
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("issue", "Issue"),
                            ("decision", "Decision"),
                            ("risk", "Risk"),
                            ("follow_up", "Follow-up"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("generated_json", models.JSONField(default=dict)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("confidence_score", models.PositiveSmallIntegerField(default=50)),
                ("reason", models.TextField(blank=True)),
                ("source_segment_index", models.PositiveIntegerField(blank=True, null=True)),
                ("source_start_time", models.FloatField(blank=True, null=True)),
                ("source_speaker", models.CharField(blank=True, max_length=255)),
                ("quote", models.TextField(blank=True)),
                ("source_analysis_version", models.PositiveIntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-confidence_score", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="decision",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.aisuggestion",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.aisuggestion",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.aisuggestion",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.aisuggestion",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.aisuggestion",
            ),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="workspace.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["owner", "status"], name="workspace_a_owner_i_4580d1_idx"),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["meeting", "status"], name="workspace_a_meeting_4e274a_idx"),
        ),
    ]
