# Generated by Django 5.1.15 on 2026-07-12 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_aisuggestion_converted_to_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoicePerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=120)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("avatar", models.URLField(blank=True, max_length=512)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("confirmed", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("voice_centroid_embedding", models.JSONField(blank=True, null=True)),
                ("best_embeddings", models.JSONField(blank=True, default=list)),
                ("embedding_dimensions", models.PositiveIntegerField(default=0)),
                ("meeting_count", models.PositiveIntegerField(default=0)),
                ("speaker_count", models.PositiveIntegerField(default=0)),
                ("total_talk_time", models.FloatField(default=0.0)),
                ("total_word_count", models.PositiveIntegerField(default=0)),
                ("avg_embedding_quality", models.FloatField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_people",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoicePersonEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("linked", "Speaker linked"),
                            ("unlinked", "Speaker unlinked"),
                            ("confirmed", "Confirmed"),
                            ("renamed", "Renamed"),
                            ("edited", "Edited"),
                            ("merged", "Merged"),
                            ("split", "Split"),
                        ],
                        max_length=16,
                    ),
                ),
                ("speaker_id", models.UUIDField(blank=True, null=True)),
                ("meeting_id", models.UUIDField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto_highlight", "Almost certain"),
                            ("highly_likely", "Highly likely"),
                            ("possible", "Possible"),
                            ("none", "Below suggestion threshold"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workspace.voiceperson",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="voiceperson",
            index=models.Index(
                fields=["owner", "-last_seen"], name="workspace_v_owner_i_d00bc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicepersonevent",
            index=models.Index(
                fields=["voice_person", "-created_at"], name="workspace_v_voice_p_1bedfe_idx"
            ),
        ),
    ]
