# Generated by Django 5.1.15 on 2026-07-08 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0006_meeting_project"),
        ("workspace", "0003_aisuggestion_converted_to_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("segment", "Transcript Segment"),
                            ("summary", "Summary"),
                            ("decision", "Decision"),
                            ("task", "Task"),
                            ("issue", "Issue"),
                            ("risk", "Risk"),
                            ("report", "Report"),
                            ("project", "Project"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("speaker", models.CharField(blank=True, max_length=255)),
                ("source_start_time", models.FloatField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspace.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "entity_type"], name="knowledge_k_owner_i_6178b4_idx"
                    ),
                    models.Index(
                        fields=["owner", "meeting"], name="knowledge_k_owner_i_d54e45_idx"
                    ),
                    models.Index(
                        fields=["owner", "project"], name="knowledge_k_owner_i_4a6776_idx"
                    ),
                    models.Index(
                        fields=["owner", "-occurred_at"], name="knowledge_k_owner_i_9ac286_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "entity_type", "entity_id"), name="uniq_knowledge_entity"
                    )
                ],
            },
        ),
    ]
