# Generated by Django 5.1.15 on 2026-07-09 07:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
        ("meetings", "0006_meeting_project"),
        ("workspace", "0003_aisuggestion_converted_to_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=128)),
                ("dimensions", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=16)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("segment", "Transcript Segment"),
                            ("summary", "Summary"),
                            ("decision", "Decision"),
                            ("task", "Task"),
                            ("issue", "Issue"),
                            ("risk", "Risk"),
                            ("report", "Report"),
                            ("project", "Project"),
                            ("person", "Person"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("superseded", "Superseded"),
                            ("merged", "Merged"),
                            ("split", "Split"),
                            ("archived", "Archived"),
                            ("reindexed", "Re-indexed"),
                            ("reembedded", "Re-embedded"),
                            ("ai_corrected", "AI corrected"),
                            ("manual_corrected", "Manually corrected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(blank=True, null=True)),
                ("supersedes_version", models.PositiveIntegerField(blank=True, null=True)),
                ("knowledge_version", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "change_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("initial", "Initial index"),
                            ("meeting_reindex", "Meeting re-index"),
                            ("ai_suggestion", "AI suggestion"),
                            ("manual_edit", "Manual edit"),
                            ("merge", "Merge"),
                            ("split", "Split"),
                            ("reembed", "Re-embed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRetrieval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("kind", models.CharField(default="org_chat", max_length=24)),
                ("question", models.TextField(blank=True)),
                ("knowledge_version", models.PositiveIntegerField(db_index=True, default=0)),
                ("retrieved_items", models.JSONField(blank=True, default=list)),
                ("ranking_scores", models.JSONField(blank=True, default=dict)),
                ("response_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("llm_provider", models.CharField(blank=True, max_length=32)),
                ("llm_model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                ("found", models.BooleanField(default=True)),
                ("answer_preview", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "indexed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("trigger", models.CharField(blank=True, max_length=32)),
                ("reason", models.TextField(blank=True)),
                ("meetings", models.PositiveIntegerField(default=0)),
                ("projects", models.PositiveIntegerField(default=0)),
                ("tasks", models.PositiveIntegerField(default=0)),
                ("decisions", models.PositiveIntegerField(default=0)),
                ("risks", models.PositiveIntegerField(default=0)),
                ("items", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="knowledgeitem",
            name="uniq_knowledge_entity",
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="change_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="change_source",
            field=models.CharField(
                choices=[
                    ("initial", "Initial index"),
                    ("meeting_reindex", "Meeting re-index"),
                    ("ai_suggestion", "AI suggestion"),
                    ("manual_edit", "Manual edit"),
                    ("merge", "Merge"),
                    ("split", "Split"),
                    ("reembed", "Re-embed"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="confidence",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="confidence_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="consensus_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="is_current",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="knowledge_version",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="retrieval_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="supersedes_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="valid_from",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="valid_to",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspace.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeitem",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("meeting", "Meeting"),
                    ("segment", "Transcript Segment"),
                    ("summary", "Summary"),
                    ("decision", "Decision"),
                    ("task", "Task"),
                    ("issue", "Issue"),
                    ("risk", "Risk"),
                    ("report", "Report"),
                    ("project", "Project"),
                    ("person", "Person"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="embeddingversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="embeddingversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="embedding_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.embeddingversion",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["owner", "is_current"], name="knowledge_k_owner_i_807b52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["owner", "entity_type", "entity_id", "-version"],
                name="knowledge_k_owner_i_c35838_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["owner", "valid_from", "valid_to"], name="knowledge_k_owner_i_c1e693_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeitem",
            constraint=models.UniqueConstraint(
                fields=("owner", "entity_type", "entity_id", "version"),
                name="uniq_knowledge_entity_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("is_deleted", False)),
                fields=("owner", "entity_type", "entity_id"),
                name="uniq_current_knowledge_entity",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="knowledge.knowledgeitem",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="meetings.meeting",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrieval",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrieval",
            name="embedding_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.embeddingversion",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrieval",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_retrievals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrieval",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeversion",
            name="embedding_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.embeddingversion",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeversion",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingversion",
            constraint=models.UniqueConstraint(
                fields=("provider", "model", "dimensions"), name="uniq_embedding_version"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeevent",
            index=models.Index(
                fields=["owner", "entity_type", "entity_id", "-created_at"],
                name="knowledge_k_owner_i_ec9ce4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeevent",
            index=models.Index(
                fields=["owner", "event_type", "-created_at"], name="knowledge_k_owner_i_64925a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeevent",
            index=models.Index(
                fields=["owner", "-knowledge_version"], name="knowledge_k_owner_i_d65349_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeretrieval",
            index=models.Index(
                fields=["owner", "-created_at"], name="knowledge_k_owner_i_3fc553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeretrieval",
            index=models.Index(
                fields=["owner", "kind", "-created_at"], name="knowledge_k_owner_i_d0350d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeversion",
            index=models.Index(fields=["owner", "-version"], name="knowledge_k_owner_i_40f701_idx"),
        ),
        migrations.AddConstraint(
            model_name="knowledgeversion",
            constraint=models.UniqueConstraint(
                fields=("owner", "version"), name="uniq_knowledge_version"
            ),
        ),
    ]
