# Generated by Django 5.1.15 on 2026-07-09 07:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_embeddingversion_knowledgeevent_knowledgeretrieval_and_more"),
        ("meetings", "0006_meeting_project"),
        ("workspace", "0003_aisuggestion_converted_to_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeConsensus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("topic", models.CharField(db_index=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("business", "Business"),
                            ("timeline", "Timeline"),
                            ("risk", "Risk"),
                            ("architecture", "Architecture"),
                            ("security", "Security"),
                            ("customer", "Customer"),
                            ("performance", "Performance"),
                            ("compliance", "Compliance"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("current_position", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("support_count", models.PositiveIntegerField(default=0)),
                ("opposition_count", models.PositiveIntegerField(default=0)),
                ("last_changed", models.DateTimeField(blank=True, null=True)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("stable", "Stable"),
                            ("strengthening", "Strengthening"),
                            ("weakening", "Weakening"),
                            ("shifting", "Shifting"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("stability_score", models.FloatField(default=100.0)),
                ("reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_consensuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("topic", models.CharField(db_index=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("business", "Business"),
                            ("timeline", "Timeline"),
                            ("risk", "Risk"),
                            ("architecture", "Architecture"),
                            ("security", "Security"),
                            ("customer", "Customer"),
                            ("performance", "Performance"),
                            ("compliance", "Compliance"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("positions", models.JSONField(blank=True, default=list)),
                ("decision_count", models.PositiveIntegerField(default=0)),
                ("meeting_count", models.PositiveIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspace.decision",
                    ),
                ),
                (
                    "resolved_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consensus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicts",
                        to="knowledge.knowledgeconsensus",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeConsensusRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("support_count", models.PositiveIntegerField(default=0)),
                ("opposition_count", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "consensus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="knowledge.knowledgeconsensus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("recorded_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="knowledgeconsensus",
            index=models.Index(fields=["owner", "topic"], name="knowledge_k_owner_i_578bc8_idx"),
        ),
        migrations.AddConstraint(
            model_name="knowledgeconsensus",
            constraint=models.UniqueConstraint(
                fields=("owner", "topic"), name="uniq_knowledge_consensus"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeconflict",
            index=models.Index(fields=["owner", "status"], name="knowledge_k_owner_i_f3ac6b_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeconflict",
            index=models.Index(fields=["owner", "category"], name="knowledge_k_owner_i_824e10_idx"),
        ),
        migrations.AddConstraint(
            model_name="knowledgeconflict",
            constraint=models.UniqueConstraint(
                fields=("owner", "topic"), name="uniq_knowledge_conflict"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeconsensusrevision",
            index=models.Index(
                fields=["consensus", "recorded_at"], name="knowledge_k_consens_87f20b_idx"
            ),
        ),
    ]
