# Generated by Django 5.1.15 on 2026-07-09 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_knowledgeconsensus_knowledgeconflict_and_more"),
        ("workspace", "0003_aisuggestion_converted_to_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(db_index=True, max_length=200)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("knowledge_conflict", "Knowledge conflict"),
                            ("decision_instability", "Decision instability"),
                            ("repeated_blocker", "Repeated blocker"),
                            ("overdue_risk", "Overdue risk"),
                            ("declining_health", "Declining project health"),
                            ("customer_complaint", "Repeated customer complaint"),
                            ("ai_confidence_drop", "AI confidence drop"),
                            ("knowledge_outdated", "Knowledge becoming outdated"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["owner", "status"], name="knowledge_e_owner_i_6521d0_idx"),
                    models.Index(
                        fields=["owner", "alert_type"], name="knowledge_e_owner_i_fe1bd5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("owner", "key"), name="uniq_executive_alert")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveExplanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_version", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("scope", models.CharField(default="organization", max_length=24)),
                ("metric_key", models.CharField(db_index=True, max_length=64)),
                ("label", models.CharField(blank=True, max_length=128)),
                ("value", models.FloatField(blank=True, null=True)),
                ("formula", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "scope", "metric_key"), name="uniq_executive_explanation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("overall_health", models.FloatField(default=0.0)),
                ("workspace_score", models.FloatField(default=0.0)),
                ("knowledge_items", models.PositiveIntegerField(default=0)),
                ("meetings", models.PositiveIntegerField(default=0)),
                ("tasks_total", models.PositiveIntegerField(default=0)),
                ("tasks_done", models.PositiveIntegerField(default=0)),
                ("tasks_blocked", models.PositiveIntegerField(default=0)),
                ("open_risks", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("decisions", models.PositiveIntegerField(default=0)),
                ("open_conflicts", models.PositiveIntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("decision_stability", models.FloatField(default=0.0)),
                ("ai_retrievals", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("recorded_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "recorded_at"], name="knowledge_e_owner_i_c2fcdb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutivePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_version", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("metric", models.CharField(db_index=True, max_length=40)),
                ("current_value", models.FloatField(default=0.0)),
                ("expected_value", models.FloatField(default=0.0)),
                ("horizon_days", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                ("message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "metric", "-generated_at"],
                        name="knowledge_e_owner_i_59b794_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_version", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("key", models.CharField(db_index=True, max_length=200)),
                ("priority", models.CharField(blank=True, max_length=12)),
                ("recommendation", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("impact", models.JSONField(blank=True, default=dict)),
                ("related_projects", models.JSONField(blank=True, default=list)),
                ("consensus", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "key"), name="uniq_executive_recommendation"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveTrendPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granularity",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("metric", models.CharField(db_index=True, max_length=40)),
                ("period_start", models.DateTimeField(db_index=True)),
                ("value", models.FloatField(default=0.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_trend_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "metric", "granularity", "period_start"],
                        name="knowledge_e_owner_i_909378_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "granularity", "metric", "period_start"),
                        name="uniq_executive_trend_point",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_version", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("overall_health_score", models.FloatField(default=0.0)),
                (
                    "overall_health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="good",
                        max_length=12,
                    ),
                ),
                ("workspace_score", models.FloatField(default=0.0)),
                ("health", models.JSONField(blank=True, default=dict)),
                ("score", models.JSONField(blank=True, default=dict)),
                ("analytics", models.JSONField(blank=True, default=dict)),
                ("organization_insights", models.JSONField(blank=True, default=dict)),
                ("knowledge_freshness", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("owner",), name="uniq_organization_snapshot")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_version", models.PositiveIntegerField(default=0)),
                ("knowledge_version", models.PositiveIntegerField(default=0)),
                ("consensus_version", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("overall_health_score", models.FloatField(default=0.0)),
                (
                    "overall_health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="good",
                        max_length=12,
                    ),
                ),
                ("memory_score", models.JSONField(blank=True, default=dict)),
                ("signals", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="workspace.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "-overall_health_score"],
                        name="knowledge_p_owner_i_ddef32_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "project"), name="uniq_project_snapshot"
                    )
                ],
            },
        ),
    ]
