# Generated by Django 5.1.15 on 2026-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_executivealert_executiveexplanation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executiveexplanation",
            name="scope",
            field=models.CharField(default="organization", max_length=48),
        ),
    ]
