# Generated by Django 5.1.15 on 2026-07-08 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("stage", models.CharField(blank=True, max_length=64)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("progress", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="current_stage",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="pipeline",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="queue_name",
            field=models.CharField(db_index=True, default="default", max_length=64),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="stack_trace",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="worker_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("meeting_processing", "Meeting Processing"),
                    ("ocr", "OCR"),
                    ("image_generation", "Image Generation"),
                    ("report_export", "Report Export"),
                    ("email", "Email"),
                    ("video_processing", "Video Processing"),
                    ("thumbnail", "Thumbnail Generation"),
                    ("cleanup", "Cleanup"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="priority",
            field=models.IntegerField(
                choices=[(10, "Critical"), (50, "High"), (100, "Normal"), (200, "Low")],
                db_index=True,
                default=100,
            ),
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("waiting", "Waiting"),
                    ("running", "Running"),
                    ("retrying", "Retrying"),
                    ("paused", "Paused"),
                    ("cancellation_requested", "Cancellation Requested"),
                    ("canceled", "Cancelled"),
                    ("succeeded", "Completed"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="queued",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["pipeline", "status"], name="jobs_backgr_pipelin_9588c2_idx"
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_logs",
                to="jobs.backgroundjob",
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(
                fields=["job", "created_at"], name="jobs_joblog_job_id_c8c1ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(
                fields=["job", "stage"], name="jobs_joblog_job_id_2b5e45_idx"
            ),
        ),
    ]
