# Generated by Django 5.1.15 on 2026-07-08 14:23

import apps.meetings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=16)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Manual Upload"),
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                            ("ms_teams", "Microsoft Teams"),
                            ("mobile_recording", "Mobile Recording"),
                            ("voice_recorder", "Voice Recorder"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="manual_upload",
                        max_length=32,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retrying", "Retrying"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("citations", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive Summary"),
                            ("detailed_summary", "Detailed Summary"),
                            ("bullet_summary", "Bullet Summary"),
                            ("meeting_minutes", "Meeting Minutes"),
                            ("action_items", "Action Items"),
                            ("decisions", "Decisions"),
                            ("risks", "Risks"),
                            ("follow_ups", "Follow Ups"),
                            ("deadlines", "Deadlines"),
                            ("keywords", "Keywords"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("raw_output", models.JSONField(default=dict)),
                ("edited_output", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_outputs",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeetingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("upload_started", "Upload started"),
                            ("upload_completed", "Upload completed"),
                            ("file_stored", "File stored"),
                            ("validation_started", "Validation started"),
                            ("validation_completed", "Validation completed"),
                            ("validation_failed", "Validation failed"),
                            ("duplicate_detected", "Duplicate detected"),
                            ("new_version", "New version uploaded"),
                            ("audio_extracted", "Audio extracted"),
                            ("queued", "Queued for processing"),
                            ("processing_started", "Processing started"),
                            ("processing_completed", "Processing completed"),
                            ("processing_failed", "Processing failed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("api", "API"),
                            ("worker", "Worker"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeetingFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.meetings.models.meeting_file_path,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("stored_filename", models.CharField(blank=True, max_length=255)),
                ("file_extension", models.CharField(blank=True, max_length=16)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "media_kind",
                    models.CharField(
                        blank=True,
                        choices=[("audio", "Audio"), ("video", "Video")],
                        max_length=16,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("stored", "Stored"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("validation_report", models.JSONField(blank=True, default=dict)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.meetings.models.thumbnail_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("meeting", "-version"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("container", models.CharField(blank=True, max_length=32)),
                ("audio_codec", models.CharField(blank=True, max_length=32)),
                ("video_codec", models.CharField(blank=True, max_length=32)),
                ("bitrate", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("channels", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_rate", models.FloatField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_metadata",
                        to="meetings.meetingfile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeetingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "background_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_link",
                        to="jobs.backgroundjob",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_jobs",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("file_validation", "File Validation"),
                            ("audio_extraction", "Audio Extraction"),
                            ("audio_conversion", "Audio Conversion"),
                            ("speech_recognition", "Speech Recognition"),
                            ("transcript_cleanup", "Transcript Cleanup"),
                            ("chunking", "Chunking"),
                            ("ai_summary", "AI Summary"),
                            ("action_items", "Action Items"),
                            ("decisions", "Decisions"),
                            ("keywords", "Keywords"),
                            ("export", "Export"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "background_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="jobs.backgroundjob",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="Ordinal position within the transcript."
                    ),
                ),
                (
                    "start_time",
                    models.FloatField(help_text="Segment start, in seconds."),
                ),
                ("end_time", models.FloatField(help_text="Segment end, in seconds.")),
                ("speaker", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("meeting", "index"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("declared_size", models.BigIntegerField(blank=True, null=True)),
                ("received_bytes", models.BigIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(blank=True, null=True)),
                ("received_chunks", models.PositiveIntegerField(default=0)),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["owner", "processing_status"],
                name="meetings_me_owner_i_ad0fbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["owner", "-created_at"], name="meetings_me_owner_i_fdf48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["meeting", "created_at"], name="meetings_ch_meeting_41d894_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aioutput",
            constraint=models.UniqueConstraint(
                fields=("meeting", "kind"), name="uniq_output_kind_per_meeting"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingevent",
            index=models.Index(
                fields=["meeting", "created_at"], name="meetings_me_meeting_f7d31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingfile",
            index=models.Index(
                fields=["meeting", "is_current"], name="meetings_me_meeting_6b35ab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingfile",
            constraint=models.UniqueConstraint(
                fields=("meeting", "version"), name="uniq_file_version_per_meeting"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingjob",
            index=models.Index(
                fields=["meeting", "-created_at"], name="meetings_me_meeting_3ff6e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["meeting", "stage"], name="meetings_pr_meeting_ac7732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["meeting", "index"], name="meetings_tr_meeting_fd6bca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transcriptsegment",
            constraint=models.UniqueConstraint(
                fields=("meeting", "index"), name="uniq_segment_index_per_meeting"
            ),
        ),
    ]
