# Generated by Django 5.1.15 on 2026-07-08 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_mediametadata_height_mediametadata_width_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("executive_summary", models.TextField(blank=True)),
                ("detailed_summary", models.TextField(blank=True)),
                ("bullet_summary", models.JSONField(blank=True, default=list)),
                ("meeting_minutes", models.TextField(blank=True)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("decisions", models.JSONField(blank=True, default=list)),
                ("risks", models.JSONField(blank=True, default=list)),
                ("follow_ups", models.JSONField(blank=True, default=list)),
                ("deadlines", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.TextField(blank=True)),
                ("parsed_response", models.JSONField(blank=True, default=dict)),
                ("model_used", models.CharField(blank=True, max_length=64)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                ("inference_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("chunks", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="meetings.meetingfile",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("meeting", "-version"),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["meeting", "is_current"], name="meetings_ai_meeting_639beb_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "version"), name="uniq_analysis_version_per_meeting"
                    )
                ],
            },
        ),
    ]
