# Generated by Django 5.1.15 on 2026-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_messagecitation_chatmessage_found_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="issues",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
