# Generated by Django 5.1.15 on 2026-07-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_aianalysis_issues"),
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="workspace.project",
            ),
        ),
    ]
