# Generated by Django 5.1.15 on 2026-07-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_meeting_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
