# Generated by Django 5.1.15 on 2026-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_meeting_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="output_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="meeting",
            name="ai_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="meeting",
            name="transcript_language",
            field=models.CharField(default="original", max_length=16),
        ),
        migrations.AddField(
            model_name="transcript",
            name="target_language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="transcript",
            name="translated_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="translation_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="translation_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="translation_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="translated_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_upload", "Manual Upload"),
                    ("live", "Live Recording"),
                    ("zoom", "Zoom"),
                    ("google_meet", "Google Meet"),
                    ("ms_teams", "Microsoft Teams"),
                    ("mobile_recording", "Mobile Recording"),
                    ("voice_recorder", "Voice Recorder"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="manual_upload",
                max_length=32,
            ),
        ),
    ]
