# Generated by Django 5.1.15 on 2026-07-11 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_aianalysis_output_language_meeting_ai_language_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveMeetingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("paused", "Paused"),
                            ("finalizing", "Finalizing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="recording",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=32)),
                ("media_kind", models.CharField(blank=True, max_length=16)),
                ("file_extension", models.CharField(default="webm", max_length=8)),
                ("meeting_language", models.CharField(blank=True, max_length=16)),
                ("transcript_language", models.CharField(default="original", max_length=16)),
                ("ai_language", models.CharField(blank=True, max_length=16)),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("bytes_received", models.BigIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("last_committed_time", models.FloatField(default=0.0)),
                ("live_summary", models.TextField(blank=True)),
                ("live_ai", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_session",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LiveTranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("index", models.PositiveIntegerField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("speaker", models.CharField(blank=True, max_length=100)),
                ("text", models.TextField()),
                ("translated_text", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meetings.livemeetingsession",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("session", "index"),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="livemeetingsession",
            index=models.Index(
                fields=["owner", "status", "-created_at"], name="meetings_li_owner_i_54d872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livetranscriptsegment",
            index=models.Index(fields=["session", "index"], name="meetings_li_session_2ffb15_idx"),
        ),
    ]
