# Generated by Django 5.1.15 on 2026-07-11 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0009_livemeetingsession_livetranscriptsegment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="meeting",
            name="source_url",
            field=models.URLField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_upload", "Manual Upload"),
                    ("live", "Live Recording"),
                    ("screen_recording", "Screen Recording"),
                    ("webcam_recording", "Webcam Recording"),
                    ("zoom", "Zoom"),
                    ("google_meet", "Google Meet"),
                    ("ms_teams", "Microsoft Teams"),
                    ("mobile_recording", "Mobile Recording"),
                    ("voice_recorder", "Voice Recorder"),
                    ("public_video", "Public Video"),
                    ("podcast", "Podcast"),
                    ("rss_feed", "RSS Feed"),
                    ("direct_url", "Direct URL"),
                    ("batch_import", "Batch Import"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="manual_upload",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MediaImportSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=32)),
                ("provider_id", models.CharField(blank=True, max_length=32)),
                ("source_url", models.URLField(max_length=1024)),
                ("platform", models.CharField(blank=True, max_length=64)),
                ("platform_id", models.CharField(blank=True, max_length=128)),
                ("episode_id", models.CharField(blank=True, max_length=64)),
                ("episode_guid", models.CharField(blank=True, max_length=512)),
                ("playlist", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("downloading", "Downloading"),
                            ("downloaded", "Downloaded"),
                            ("validating", "Validating"),
                            ("importing", "Importing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1024)),
                ("published_at", models.CharField(blank=True, max_length=64)),
                ("license", models.CharField(blank=True, max_length=128)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("media_kind", models.CharField(blank=True, max_length=16)),
                ("requested_media", models.CharField(default="video", max_length=16)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("importer_version", models.CharField(blank=True, max_length=16)),
                ("meeting_language", models.CharField(blank=True, max_length=16)),
                ("transcript_language", models.CharField(default="original", max_length=16)),
                ("ai_language", models.CharField(blank=True, max_length=16)),
                ("on_duplicate", models.CharField(default="reject", max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=48)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_session",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "status", "-created_at"],
                        name="meetings_me_owner_i_6cb4fe_idx",
                    ),
                    models.Index(
                        fields=["owner", "source_url"], name="meetings_me_owner_i_5e134c_idx"
                    ),
                    models.Index(
                        fields=["platform", "platform_id"], name="meetings_me_platfor_af651f_idx"
                    ),
                ],
            },
        ),
    ]
