# Generated by Django 5.1.15 on 2026-07-11 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_meeting_source_metadata_meeting_source_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(max_length=32)),
                ("diarization_label", models.CharField(blank=True, max_length=32)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("confirmed", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, max_length=16)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("avatar", models.URLField(blank=True, max_length=512)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("suggested_name", models.CharField(blank=True, max_length=120)),
                ("suggested_confidence", models.FloatField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("recognition_confidence", models.FloatField(blank=True, null=True)),
                ("talk_time_seconds", models.FloatField(default=0.0)),
                ("segment_count", models.PositiveIntegerField(default=0)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                ("workspace_person", models.CharField(blank=True, max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("meeting", "label"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="speaker_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="meetings.speaker",
            ),
        ),
        migrations.AddIndex(
            model_name="speaker",
            index=models.Index(fields=["meeting", "label"], name="meetings_sp_meeting_37f451_idx"),
        ),
    ]
