# Generated by Django 5.1.15 on 2026-07-12 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0011_speaker_transcriptsegment_speaker_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerQualitySignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("signal_quality", models.FloatField(blank=True, null=True)),
                ("noise_score", models.FloatField(blank=True, null=True)),
                ("speech_duration", models.FloatField(default=0.0)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                ("overlap_ratio", models.FloatField(blank=True, null=True)),
                ("silence_ratio", models.FloatField(blank=True, null=True)),
                ("embedding_quality_score", models.FloatField(blank=True, null=True)),
                ("usable_segments", models.PositiveIntegerField(default=0)),
                ("total_segments", models.PositiveIntegerField(default=0)),
                ("approximate", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speaker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality",
                        to="meetings.speaker",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-signal_quality",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeakerEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("segment", "Segment"),
                            ("centroid", "Centroid"),
                            ("best_n", "Best-N Representative"),
                        ],
                        max_length=16,
                    ),
                ),
                ("vector", models.JSONField()),
                ("dimensions", models.PositiveIntegerField(default=0)),
                ("segment_index", models.IntegerField(blank=True, null=True)),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(default=0.0)),
                ("quality", models.FloatField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model", models.CharField(blank=True, max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="meetings.speaker",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("speaker", "kind", "rank", "segment_index"),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["speaker", "kind"], name="meetings_sp_speaker_e4f973_idx")
                ],
            },
        ),
    ]
