# Generated by Django 5.1.15 on 2026-07-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0012_speakerqualitysignal_speakerembedding"),
        ("workspace", "0004_voiceperson_voicepersonevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="voice_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speakers",
                to="workspace.voiceperson",
            ),
        ),
    ]
